#ifndef __VEIGAR_MSGPACK_VERSION_MASTER_HPP // Add by msgpack.py
#define __VEIGAR_MSGPACK_VERSION_MASTER_HPP
#define MSGPACK_VERSION_MAJOR    6
#define MSGPACK_VERSION_MINOR    1
#define MSGPACK_VERSION_REVISION 0

#endif // !__VEIGAR_MSGPACK_VERSION_MASTER_HPP